### PR TITLE
sugargame

### PR DESCRIPTION
**Pull request by ayushnawal**
@quozl

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed;

* [ ] not part of Sugar desktop.

**Comment by ayushnawal** [comment]
done :grimacing:

**Comment by quozl** [comment]
Wording we use in other activities in this classification is "is not part of the Sugar desktop, but can be added."

**Comment by srevinsaju** [comment]
On testing your port, I have found an error on both master and your port branch
image

Test methods to recreate the error:
* click the play button
* change the slider between the bulbs
* do some changes to the numbers
* press the playbutton again

Tested, no other errors other than this one

**Comment by ayushnawal** [comment]
@srevinsaju I tested the port again, I am sure it is not because of my changes.

also, I tried to fix it but found that `randint` already contains both arguments as integers.
I'm puzzled because this type of error occurs when one of them is not an integer.

can you help me here?

**Comment by srevinsaju** [comment]
@ayushnawal it is at line 320 in Numbers.py, gives the second args as float. to prove it
```
print(g.max_n, type(g.max_n)
```
Should give the long decimal value, and <class 'float'> instead of <class 'int'> 
It might have been created before the port, but its easy to fix it :)

**Comment by srevinsaju** [comment]
@ayushnawal mentioned this https://github.com/sugarlabs/numbers/pull/4#issuecomment-578316807 because you told that both of the args were integer in the previous comment. I have created a  PR https://github.com/ayushnawal/numbers/pull/1 on your fork, please review, and we are ready to merge :) Thanks @ayushnawal

**Comment by ayushnawal** [comment]
@srevinsaju thanks for the help.

I already tried fixing it with changes you did in this [pr](https://github.com/ayushnawal/numbers/pull/1)

when i tested the activity again, i saw this in logs

> Traceback (most recent call last):
  File "/home/ayush/activities/numbers/Numbers.py", line 543, in run
    self.animation()
  File "/home/ayush/activities/numbers/Numbers.py", line 395, in animation
    self.anim_update()
  File "/home/ayush/activities/numbers/Numbers.py", line 380, in anim_update
    g.aim = random.randint(5, self.anim_mx)
  File "/usr/lib/python2.7/random.py", line 244, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 200, in randrange
    raise ValueError, "non-integer stop for randrange()"
ValueError: non-integer stop for randrange()

Steps:
* press play button
* change slider between the bulbs

Did you face it or any idea about it?

Thanks again :)

**Comment by srevinsaju** [comment]
@ayushnawal I fixed that error too on the PR, this wasn't an error caused by port, but now it has caused another issue, the slider isn't working properly, i am currently debugging on how to  fix it, if you have any commits, you can push it here

**Comment by srevinsaju** [comment]
@quozl this error mentioned https://github.com/sugarlabs/numbers/pull/4#issuecomment-578265060 here,  had been existing before and after the port, so, I guess we can merge this port and continue with an open issue, I tried fixing it, but was unsuccessful, 
@ayushnawal, it is good that you didn't merge my PR. We will continue with the porting work you have done perfectly.

**Comment by ayushnawal** [comment]
Thanks @srevinsaju for the review.
I also tried fixing it, will try back later with a fresh mind.
opening an [issue](https://github.com/sugarlabs/numbers/issues/5) for the same.
@quozl activity ready for the port.

**Pull request merged**
